<?php
/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/02/2015
 */
// This snippet is adopted from Stripe SDK.
if (!function_exists('curl_init')) {
  throw new Exception('APIv3SandboxLib needs the CURL PHP extension.');
}
if (!function_exists('json_decode')) {
  throw new Exception('APIv3SandboxLib needs the JSON PHP extension.');
}
if (!function_exists('mb_detect_encoding')) {
  throw new Exception('APIv3SandboxLib needs the Multibyte String PHP extension.');
}

// This dependency shall be resolved by composer
require_once('packages/apimatic/unirest-php/lib/Unirest.php');

// APIMATIC Helper Files
require_once(dirname(__FILE__) . '/APIv3SandboxLib/APIHelper.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/APIException.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Configuration.php');

// Controllers
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Controllers/CdrsController.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Controllers/InventoryController.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Controllers/RegulationController.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Controllers/OrderingController.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Controllers/ConfigurationController.php');

// Models
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/DidIdListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/DidIdModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CreateSmsLinkModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/ACapacityGroupSaveModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/FaxUriSaveModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/BlurbModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/AVoiceUriSaveModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/SmsLinkSaveModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/SmsLinkGroupSaveModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/StatusModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/FileListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/DidModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CallerIdModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/DidOtherOptionsModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/DidListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CreditPackageModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CreditPackageListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/FeatureModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/ZoneListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/RegulationRequirementModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/TrunkModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/TrunkListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/StateModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/StateListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/DidGroupModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/RestrictionModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/RestrictionListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/DidGroupListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/FeatureListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CountryModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CountryListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/AddressExtraFieldModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/AddressModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/AddressIdentifierModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/AddressListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/ZipCodeModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/ZipCodeListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/AddressRejectionReasonModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/AddressValidResponseModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/AccountBalanceModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/DidCartItemModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CapacityCartItemModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CreditPackageCartItemModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/OrderProductModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CartModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/ProductCheckoutModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CartCheckoutModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/OrderModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/OrderListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/PeerModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/ConfigurationStatusModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/ConfigurationStatusListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CapacityGroupModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CapacityGroupListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/FaxUriModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/FaxUriListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/VoiceUriModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/VoiceUriListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/PopModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/PopListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/SmsLinkGroupModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/SmsLinkGroupListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/IdModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/SmsLinkModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/SmsLinkListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CartCreateModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CartItemModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/DidConfigurationModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CapacityGroupSaveModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/CartListModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/VoiceUriSaveModel.php');
require_once(dirname(__FILE__) . '/APIv3SandboxLib/Models/QuantityModel.php');
