<?php
/*
 * ProvisioningAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 01/06/2015
 */

class Configuration {
    //The base Uri for API calls
    const BASEURI = 'http://sandbox.voxbone.com/ws-voxbone';

    public static $BasicAuthUserName = "username";
    public static $BasicAuthPassword = "password";
}
