<?php
/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/02/2015
 */

class AccountBalanceModel {
    /**
     * The current balance of your account
     * @param double $balance public property
     */
    protected $balance;

    /**
     * The threshold under which the account will be automatically refilled
     * @param int|null $threshold public property
     */
    protected $threshold;

    /**
     * The currency of your account
     * @param string $currency public property
     */
    protected $currency;

    /**
     * A flag indicating if the automatic refill is active or not
     * @param bool $active public property
     */
    protected $active;

    /**
	 * Constructor to set initial or default values of member properties
	 * @param   double $balance    Initialization value for the property $this->balance
	 * @param   int|null $threshold    Initialization value for the property $this->threshold
	 * @param   string $currency    Initialization value for the property $this->currency
	 * @param   bool $active    Initialization value for the property $this->active
	 */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->balance = func_get_arg(0);
            $this->threshold = func_get_arg(1);
            $this->currency = func_get_arg(2);
            $this->active = func_get_arg(3);
        }
    }

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }

    /**
     * Encode this object to JSON
     */
    public function to_json()
    {
        $json = array();
        foreach($this as $key => $value) {
            $json[$key] = $value;
        }
        return $json;
    }
}