<?php
/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/02/2015
 */

class CapacityGroupModel {
    /**
     * The identifier of the capacity group
     * @param int $capacityGroupId public property
     */
    protected $capacityGroupId;

    /**
     * The maximum capacity of the capacity group
     * @param int $maximumCapacity public property
     */
    protected $maximumCapacity;

    /**
     * The amount of DIDs currently mapped to the capacity group
     * @param int $amountOfDidsMapped public property
     */
    protected $amountOfDidsMapped;

    /**
     * A human readable description of the capacity group
     * @param string $description public property
     */
    protected $description;

    /**
	 * Constructor to set initial or default values of member properties
	 * @param   int $capacityGroupId    Initialization value for the property $this->capacityGroupId
	 * @param   int $maximumCapacity    Initialization value for the property $this->maximumCapacity
	 * @param   int $amountOfDidsMapped    Initialization value for the property $this->amountOfDidsMapped
	 * @param   string $description    Initialization value for the property $this->description
	 */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->capacityGroupId = func_get_arg(0);
            $this->maximumCapacity = func_get_arg(1);
            $this->amountOfDidsMapped = func_get_arg(2);
            $this->description = func_get_arg(3);
        }
    }

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }

    /**
     * Encode this object to JSON
     */
    public function to_json()
    {
        $json = array();
        foreach($this as $key => $value) {
            $json[$key] = $value;
        }
        return $json;
    }
}