<?php
/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/02/2015
 */

class DidModel {
    /**
     * The identifier of the DID
     * @param int $didId public property
     */
    protected $didId;

    /**
     * The E164 of the DID
     * @param string $e164 public property
     */
    protected $e164;

    /**
     * The DID type
     * @param string $didType public property
     */
    protected $didType;

    /**
     * The three letter identifier for the DID's country
     * @param string $countryCodeA3 public property
     */
    protected $countryCodeA3;

    /**
     * The name of the DID's city
     * @param string|null $cityName public property
     */
    protected $cityName;

    /**
     * The DID's area code
     * @param string $areaCode public property
     */
    protected $areaCode;

    /**
     * The identifier of the voice uri the DID is mapped to
     * @param int|null $voiceUriId public property
     */
    protected $voiceUriId;

    /**
     * The identifier of the fax uri the DID is mapped to
     * @param int|null $faxUriId public property
     */
    protected $faxUriId;

    /**
     * The identifier of the sms link group the DID is mapped to
     * @param int|null $smsLinkGroupId public property
     */
    protected $smsLinkGroupId;

    /**
     * The reference for the DID's order
     * @param string $orderReference public property
     */
    protected $orderReference;

    /**
     * The amount of channels available for this DID
     * @param int $channels public property
     */
    protected $channels;

    /**
     * The POP the DID is currently mapped to
     * @param string $delivery public property
     */
    protected $delivery;

    /**
     * The identifier for the trunk the DID is currently mapped to
     * @param int $trunkId public property
     */
    protected $trunkId;

    /**
     * The identifier for the capacity group the DID is currently mapped to
     * @param int|null $capacityGroupId public property
     */
    protected $capacityGroupId;

    /**
     * The identifier for the DID's didGroup
     * @param int $didGroupId public property
     */
    protected $didGroupId;

    /**
     * The identifier for the address linked to this DID
     * @param int|null $regulationAddressId public property
     */
    protected $regulationAddressId;

    /**
     * A flag indicating if the DID uses srv lookup
     * @param bool $srvLookup public property
     */
    protected $srvLookup;

    /**
     * A flag indicating if dnis is enabled for the DID
     * @param bool $dnisEnabled public property
     */
    protected $dnisEnabled;

    /**
     * A flag indicating if ordinary calls are blocked on this DID
     * @param bool $blockOrdinary public property
     */
    protected $blockOrdinary;

    /**
     * A flag indicating if cellular calls are blocked on this DID
     * @param bool $blockCellular public property
     */
    protected $blockCellular;

    /**
     * A flag indicating if payphone calls are blocked on this DID
     * @param bool $blockPayphone public property
     */
    protected $blockPayphone;

    /**
     * A flag indicating if SMS Outbound is activated on this DID
     * @param bool $smsOutbound public property
     */
    protected $smsOutbound;

    /**
     * A flag indicating if WebRTC is activated on this DID
     * @param bool $webRtc public property
     */
    protected $webRtc;

    /**
     * The DID's caller id settings
     * @param CallerIdModel $callerId public property
     */
    protected $callerId;

    /**
     * The DID's cli privacy settings
     * @param string $cliPrivacy public property
     */
    protected $cliPrivacy;

    /**
     * The DID's in-call configuration
     * @param DidOtherOptionsModel $otherOptions public property
     */
    protected $otherOptions;

    /**
	 * Constructor to set initial or default values of member properties
	 * @param   int $didId    Initialization value for the property $this->didId
	 * @param   string $e164    Initialization value for the property $this->e164
	 * @param   string $didType    Initialization value for the property $this->didType
	 * @param   string $countryCodeA3    Initialization value for the property $this->countryCodeA3
	 * @param   string|null $cityName    Initialization value for the property $this->cityName
	 * @param   string $areaCode    Initialization value for the property $this->areaCode
	 * @param   int|null $voiceUriId    Initialization value for the property $this->voiceUriId
	 * @param   int|null $faxUriId    Initialization value for the property $this->faxUriId
	 * @param   int|null $smsLinkGroupId    Initialization value for the property $this->smsLinkGroupId
	 * @param   string $orderReference    Initialization value for the property $this->orderReference
	 * @param   int $channels    Initialization value for the property $this->channels
	 * @param   string $delivery    Initialization value for the property $this->delivery
	 * @param   int $trunkId    Initialization value for the property $this->trunkId
	 * @param   int|null $capacityGroupId    Initialization value for the property $this->capacityGroupId
	 * @param   int $didGroupId    Initialization value for the property $this->didGroupId
	 * @param   int|null $regulationAddressId    Initialization value for the property $this->regulationAddressId
	 * @param   bool $srvLookup    Initialization value for the property $this->srvLookup
	 * @param   bool $dnisEnabled    Initialization value for the property $this->dnisEnabled
	 * @param   bool $blockOrdinary    Initialization value for the property $this->blockOrdinary
	 * @param   bool $blockCellular    Initialization value for the property $this->blockCellular
	 * @param   bool $blockPayphone    Initialization value for the property $this->blockPayphone
	 * @param   bool $smsOutbound    Initialization value for the property $this->smsOutbound
	 * @param   bool $webRtc    Initialization value for the property $this->webRtc
	 * @param   CallerIdModel $callerId    Initialization value for the property $this->callerId
	 * @param   string $cliPrivacy    Initialization value for the property $this->cliPrivacy
	 * @param   DidOtherOptionsModel $otherOptions    Initialization value for the property $this->otherOptions
	 */
    public function __construct()
    {
        if(26 == func_num_args())
        {
            $this->didId = func_get_arg(0);
            $this->e164 = func_get_arg(1);
            $this->didType = func_get_arg(2);
            $this->countryCodeA3 = func_get_arg(3);
            $this->cityName = func_get_arg(4);
            $this->areaCode = func_get_arg(5);
            $this->voiceUriId = func_get_arg(6);
            $this->faxUriId = func_get_arg(7);
            $this->smsLinkGroupId = func_get_arg(8);
            $this->orderReference = func_get_arg(9);
            $this->channels = func_get_arg(10);
            $this->delivery = func_get_arg(11);
            $this->trunkId = func_get_arg(12);
            $this->capacityGroupId = func_get_arg(13);
            $this->didGroupId = func_get_arg(14);
            $this->regulationAddressId = func_get_arg(15);
            $this->srvLookup = func_get_arg(16);
            $this->dnisEnabled = func_get_arg(17);
            $this->blockOrdinary = func_get_arg(18);
            $this->blockCellular = func_get_arg(19);
            $this->blockPayphone = func_get_arg(20);
            $this->smsOutbound = func_get_arg(21);
            $this->webRtc = func_get_arg(22);
            $this->callerId = func_get_arg(23);
            $this->cliPrivacy = func_get_arg(24);
            $this->otherOptions = func_get_arg(25);
        }
    }

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }

    /**
     * Encode this object to JSON
     */
    public function to_json()
    {
        $json = array();
        foreach($this as $key => $value) {
            $json[$key] = $value;
        }
        return $json;
    }
}