<?php
/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/02/2015
 */

class OrderProductModel {
    /**
     * The identifier of the product
     * @param int $orderProductId public property
     */
    protected $orderProductId;

    /**
     * The type of product
     * @param string $productType public property
     */
    protected $productType;

    /**
     * A human readable description of the product
     * @param string $productDescription public property
     */
    protected $productDescription;

    /**
     * The quantity of products ordered
     * @param int $quantity public property
     */
    protected $quantity;

    /**
     * The identifier of the didGroup for DID products
     * @param int $didgroupId public property
     */
    protected $didgroupId;

    /**
	 * Constructor to set initial or default values of member properties
	 * @param   int $orderProductId    Initialization value for the property $this->orderProductId
	 * @param   string $productType    Initialization value for the property $this->productType
	 * @param   string $productDescription    Initialization value for the property $this->productDescription
	 * @param   int $quantity    Initialization value for the property $this->quantity
	 * @param   int $didgroupId    Initialization value for the property $this->didgroupId
	 */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->orderProductId = func_get_arg(0);
            $this->productType = func_get_arg(1);
            $this->productDescription = func_get_arg(2);
            $this->quantity = func_get_arg(3);
            $this->didgroupId = func_get_arg(4);
        }
    }

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }

    /**
     * Encode this object to JSON
     */
    public function to_json()
    {
        $json = array();
        foreach($this as $key => $value) {
            $json[$key] = $value;
        }
        return $json;
    }
}