<?php
/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/02/2015
 */

class StateModel {
    /**
     * The identifier of the state
     * @param int $stateId public property
     */
    protected $stateId;

    /**
     * The name of the state
     * @param string $stateName public property
     */
    protected $stateName;

    /**
     * The two letter identifier of the state
     * @param string $stateCode public property
     */
    protected $stateCode;

    /**
     * The three letter identifier for the state's country
     * @param string $countryCodeA3 public property
     */
    protected $countryCodeA3;

    /**
	 * Constructor to set initial or default values of member properties
	 * @param   int $stateId    Initialization value for the property $this->stateId
	 * @param   string $stateName    Initialization value for the property $this->stateName
	 * @param   string $stateCode    Initialization value for the property $this->stateCode
	 * @param   string $countryCodeA3    Initialization value for the property $this->countryCodeA3
	 */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->stateId = func_get_arg(0);
            $this->stateName = func_get_arg(1);
            $this->stateCode = func_get_arg(2);
            $this->countryCodeA3 = func_get_arg(3);
        }
    }

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }

    /**
     * Encode this object to JSON
     */
    public function to_json()
    {
        $json = array();
        foreach($this as $key => $value) {
            $json[$key] = $value;
        }
        return $json;
    }
}