<?php
/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/02/2015
 */

class TrunkModel {
    /**
     * The identifier of the trunk
     * @param int $trunkId public property
     */
    protected $trunkId;

    /**
     * The zone linked to the trunk
     * @param string $zone public property
     */
    protected $zone;

    /**
     * The maximum capacity of the trunk
     * @param int $capacity public property
     */
    protected $capacity;

    /**
     * The user description of the trunk
     * @param string $description public property
     */
    protected $description;

    /**
     * The amount of DIDs currently mapped to the trunk
     * @param int $countDidsOnTrunk public property
     */
    protected $countDidsOnTrunk;

    /**
	 * Constructor to set initial or default values of member properties
	 * @param   int $trunkId    Initialization value for the property $this->trunkId
	 * @param   string $zone    Initialization value for the property $this->zone
	 * @param   int $capacity    Initialization value for the property $this->capacity
	 * @param   string $description    Initialization value for the property $this->description
	 * @param   int $countDidsOnTrunk    Initialization value for the property $this->countDidsOnTrunk
	 */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->trunkId = func_get_arg(0);
            $this->zone = func_get_arg(1);
            $this->capacity = func_get_arg(2);
            $this->description = func_get_arg(3);
            $this->countDidsOnTrunk = func_get_arg(4);
        }
    }

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }

    /**
     * Encode this object to JSON
     */
    public function to_json()
    {
        $json = array();
        foreach($this as $key => $value) {
            $json[$key] = $value;
        }
        return $json;
    }
}