<?php
/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/27/2015
 */

class Configuration {
    //The base Uri for API calls
    const BASEURI = 'https://sandbox.voxbone.com/ws-voxbone/services/rest';
	public static $BasicAuthUserName = "username";
  	public static $BasicAuthPassword = "password";
}
