<?php 
/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 04/03/2015
 */

namespace APIv3SandboxLib\Models;

use JsonSerializable;

class DidConfigurationModel implements JsonSerializable {
    /**
     * The identifiers of the DIDs to update
     * @param array $didIds public property
     */
    protected $didIds;

    /**
     * The identifier of a voice uri to apply
     * @param int $voiceUriId public property
     */
    protected $voiceUriId;

    /**
     * The identifier of an sms link group to apply
     * @param int $smsLinkGroupId public property
     */
    protected $smsLinkGroupId;

    /**
     * The identifier of a fax uri to apply
     * @param int $faxUriId public property
     */
    protected $faxUriId;

    /**
     * The identifier of a capacity group to map the numbers to
     * @param int $capacityGroupId public property
     */
    protected $capacityGroupId;

    /**
     * The identifier of a trunk to map the numbers to
     * @param int $trunkId public property
     */
    protected $trunkId;

    /**
     * The identifier of a delivery to use for the numbers
     * @param int $deliveryId public property
     */
    protected $deliveryId;

    /**
     * A flag indicating if srv lookup should be used
     * @param bool $srvLookup public property
     */
    protected $srvLookup;

    /**
     * The caller id configuration to apply
     * @param CallerIdModel $callerId public property
     */
    protected $callerId;

    /**
     * The cli privacy configuration to apply
     * @param string $cliPrivacy public property
     */
    protected $cliPrivacy;

    /**
     * The peer configuration to apply
     * @param PeerModel $peer public property
     */
    protected $peer;

    /**
     * The ringback configuration to apply
     * @param string $ringback public property
     */
    protected $ringback;

    /**
     * A flag indicating if DNIS should be enabled
     * @param bool $dnisEnabled public property
     */
    protected $dnisEnabled;

    /**
     * A flag indicating if ordinary calls should be blocked
     * @param bool $blockOrdinary public property
     */
    protected $blockOrdinary;

    /**
     * A flag indicating if cellular calls should be blocked
     * @param bool $blockCellular public property
     */
    protected $blockCellular;

    /**
     * A flag indicating if payphone calls should be blocked
     * @param bool $blockPayphone public property
     */
    protected $blockPayphone;

    /**
     * A flag indicating if sms outbound should be activated
     * @param bool $smsOutbound public property
     */
    protected $smsOutbound;

    /**
     * A flag indicating if webrtc should be activated
     * @param bool $webRtcEnabled public property
     */
    protected $webRtcEnabled;

    /**
     * A flag indicating if voxFax is activated
     * @param string $voxFaxEnabled public property
     */
    protected $voxFaxEnabled;

    /**
     * Constructor to set initial or default values of member properties
	 * @param   array             $didIds            Initialization value for the property $this->didIds         
	 * @param   int               $voiceUriId        Initialization value for the property $this->voiceUriId     
	 * @param   int               $smsLinkGroupId    Initialization value for the property $this->smsLinkGroupId 
	 * @param   int               $faxUriId          Initialization value for the property $this->faxUriId       
	 * @param   int               $capacityGroupId   Initialization value for the property $this->capacityGroupId
	 * @param   int               $trunkId           Initialization value for the property $this->trunkId        
	 * @param   int               $deliveryId        Initialization value for the property $this->deliveryId     
	 * @param   bool              $srvLookup         Initialization value for the property $this->srvLookup      
	 * @param   CallerIdModel     $callerId          Initialization value for the property $this->callerId       
	 * @param   string            $cliPrivacy        Initialization value for the property $this->cliPrivacy     
	 * @param   PeerModel         $peer              Initialization value for the property $this->peer           
	 * @param   string            $ringback          Initialization value for the property $this->ringback       
	 * @param   bool              $dnisEnabled       Initialization value for the property $this->dnisEnabled    
	 * @param   bool              $blockOrdinary     Initialization value for the property $this->blockOrdinary  
	 * @param   bool              $blockCellular     Initialization value for the property $this->blockCellular  
	 * @param   bool              $blockPayphone     Initialization value for the property $this->blockPayphone  
	 * @param   bool              $smsOutbound       Initialization value for the property $this->smsOutbound    
	 * @param   bool              $webRtcEnabled     Initialization value for the property $this->webRtcEnabled  
	 * @param   string            $voxFaxEnabled     Initialization value for the property $this->voxFaxEnabled  
     */
    public function __construct()
    {
        if(19 == func_num_args())
        {
            $this->didIds          = func_get_arg(0);
            $this->voiceUriId      = func_get_arg(1);
            $this->smsLinkGroupId  = func_get_arg(2);
            $this->faxUriId        = func_get_arg(3);
            $this->capacityGroupId = func_get_arg(4);
            $this->trunkId         = func_get_arg(5);
            $this->deliveryId      = func_get_arg(6);
            $this->srvLookup       = func_get_arg(7);
            $this->callerId        = func_get_arg(8);
            $this->cliPrivacy      = func_get_arg(9);
            $this->peer            = func_get_arg(10);
            $this->ringback        = func_get_arg(11);
            $this->dnisEnabled     = func_get_arg(12);
            $this->blockOrdinary   = func_get_arg(13);
            $this->blockCellular   = func_get_arg(14);
            $this->blockPayphone   = func_get_arg(15);
            $this->smsOutbound     = func_get_arg(16);
            $this->webRtcEnabled   = func_get_arg(17);
            $this->voxFaxEnabled   = func_get_arg(18);
        }
    }

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['didIds']          = $this->didIds;
        $json['voiceUriId']      = $this->voiceUriId;
        $json['smsLinkGroupId']  = $this->smsLinkGroupId;
        $json['faxUriId']        = $this->faxUriId;
        $json['capacityGroupId'] = $this->capacityGroupId;
        $json['trunkId']         = $this->trunkId;
        $json['deliveryId']      = $this->deliveryId;
        $json['srvLookup']       = $this->srvLookup;
        $json['callerId']        = $this->callerId;
        $json['cliPrivacy']      = $this->cliPrivacy;
        $json['peer']            = $this->peer;
        $json['ringback']        = $this->ringback;
        $json['dnisEnabled']     = $this->dnisEnabled;
        $json['blockOrdinary']   = $this->blockOrdinary;
        $json['blockCellular']   = $this->blockCellular;
        $json['blockPayphone']   = $this->blockPayphone;
        $json['smsOutbound']     = $this->smsOutbound;
        $json['webRtcEnabled']   = $this->webRtcEnabled;
        $json['voxFaxEnabled']   = $this->voxFaxEnabled;
        return $json;
    }
}