<?php
/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 04/02/2015
 */

namespace APIv3SandboxLib;

class Configuration {
    //The base Uri for API calls
    const BASEURI = 'http://sandbox.voxbone.com/ws-voxbone/services/rest';
    public static $BasicAuthUserName = "your_username";
  	public static $BasicAuthPassword = "your_password";

}
